### ISSUE TITLE
Throwing error in register function

### ISSUE THREAD

**Issue by green3g** [canjs/can-view-nodelist#27]
It appears that [parent.replacements](https://github.com/canjs/can-view-nodelist/blob/master/can-view-nodelist.js#L323) can be null at times. I'm not sure why its null but it throws an error and the app breaks. 

See below:

![image](https://user-images.githubusercontent.com/5471079/28975085-5d080ca6-78fe-11e7-9be7-665d118460b9.png)

**Comment by green3g** [comment]
So this was being caused by a helper, I had a split function that splits a string by separator and returns an array. The array was used to render a list items.

```html
{{#each split(object[field.name], ',')}}
  <li><a target="_blank" href="{{.}}">{{filename(.)}}</a></li>
{{/each}}
</ul>
```

I converted the methods to getters to try to isolate the helper and it worked using the getter so that's what I'm using as a workaround. 

UPDATE:  this doesn't appear to be related since the issue is still happening.

**Comment by phillipskevin** [comment]
@roemhildtg are you sure the `split` helper is where this issue is happening? (ie if you remove that section of your template, does the issue go away?)

**Comment by green3g** [comment]
Nope, that wasn't the issue. I removed that helper and it still occurs. Still trying to isolate the issue. 

It looks like its happening on 
`each objects as object` 
![image](https://user-images.githubusercontent.com/5471079/29031849-27651b30-7b55-11e7-8127-f19e4221a81c.png)

objects gets set when a promise resolves:

```javascript
    /**
     * The array of objects currently retrieved and in the list view. This is set
     * once the `objectsPromise` completes
     */
    objects: {
        Value: DefineList,
        get (val, setAttr) {

            const promise = this.objectsPromise;

            promise.catch((err) => {
                dev.warn('unable to complete objects request', err);
            });

            // update the list data
            promise.then((data) => {
                setAttr(data);
            });
        }
```

**Comment by green3g** [comment]
Looks like if I use `val.replace(data)` instead of `setAttr(data)` it actually fixes the issue.

**Comment by phillipskevin** [comment]
We just saw this on another project. Here is a JSBin reproducing the problem: http://jsbin.com/cejinulobu/1/edit?html,js,output.

**Comment by jeroencornelissen** [comment]
We have the same issue.
But can't pin point where it goes wrong.

**Comment by jeroencornelissen** [comment]
Narrowed it down, it also happened in an `{{#each items as item}}` loop.
When I change the loop to `{{#items}}` it works.

**Comment by phillipskevin** [comment]
Thanks for letting us know about the work-around, @jeroencornelissen. We're still planning to investigate and get a fix out soon.

**Comment by jeroencornelissen** [comment]
Thx, @phillipskevin.
FYI: I've updated your jsbin to work with `{{#items}}` and that throws a warning `"DefineMap::attr shouldn't be called"`.  We also get these warnings a lot in our app, although we don't use `.attr`.

http://jsbin.com/qixohemofu/edit?html,js,console,output

**Comment by phillipskevin** [comment]
Issue moved to [canjs/can-view-live #55](https://github.com/canjs/can-view-live/issues/55) via [**ZenHub**](https://www.zenhub.com/)
