### ISSUE TITLE
parentList.replacements keeps growing

### ISSUE THREAD

**Issue by RyanMilligan** [canjs/can-view-nodelist#42]
Scenario:

Stache sort of like this:
```
{{#each list}}
    <input type="text" value:from="name" />
{{/each}}
<a on:click="changeList()">Change</a>
```
`changeList()` should be a function that will manipulate `list` in some way, such as adding or removing elements. Each time `changeList()` is called, a nodeList will be added to the `replacements` list associated with the `each` helper, which never appears to be cleaned up. This results in a full leak of the entire UI associated with the list.

**Comment by phillipskevin** [comment]
Here is an example showing the problem: https://jsbin.com/noloqox/edit?js,output

You can see in the console in this gif that `parent.replacements` just continually grows, even when items are removed from the list:
![infinite-replacements](https://user-images.githubusercontent.com/5851984/35888890-08ec8c84-0b5f-11e8-9fad-fb5200d1e260.gif)

**Comment by phillipskevin** [comment]
This is also an issue in `can-view-nodelist@4.0`.

**Comment by justinbmeyer** [comment]
So tracking a bit of this down, when an items nodes are rendered, those nodes are registered here:

https://github.com/canjs/can-view-live/blob/master/lib/list.js#L31

I think `nodeLists.register(itemNodeList, null, parentNodeList, true);` should be:

```js
nodeLists.register(itemNodeList, null, true, true);
```

Normally, you would pass the parent node list, but can-view-live.list manages the nodelist itself.

**Comment by justinbmeyer** [comment]
verified this change does not break can-stache.  Just needs a test in can-view-live

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-view-live #93](https://github.com/canjs/can-view-live/issues/93) via [**ZenHub**](https://www.zenhub.com/)
