### ISSUE TITLE
after method fails on unparented nodes

### ISSUE THREAD

**Issue by rjgotten** [canjs/can-view-nodelist#53]
The `after` method in `can-view-nodelist` fails to take into account recently unparented DOM nodes.
It calls `domMutate.appendChild.call(last.parentNode, newFrag)` where `parentNode` may be `null`, leading to a crash.

Specifically; this happens when a node which renders with the `live.list` helper is removed in the same logic tick as when the list itself is emptied out, leading to its `addFalseyIfEmpty` branch being executed.

**Comment by justinbmeyer** [comment]
Thanks for reporting.  Usually if can-view-nodelist is throwing an error, it means something in can-view-live is broken.

So that we can create a test, are you saying that a template like:

```
{{# if(this.value) }}
  {{# for( item of this.items } }}
  {{else}}
  {{/ for }}
{{/ if }}
```

Would throw if someone did something like the following in a batch:

```js
queue.batch.start();
map.value = false;
map.items.update([])
queue.batch.stop();
```

**Comment by rjgotten** [comment]
@justinbmeyer 

There looks to be an edge case that plays out like the following:

- have two helpers, tied to elements (text nodes) both of which are removed from the DOM in the same pass. (E.g. `innerHTML = ""` to wipe it all.)
- one uses `live.list` and observes a list of items
- the other helper implements a teardown which removes some entries from the same list and _may_ empty it completely.

As the teardowns iirc run from a mutation observer, the elements the helpers are tied to are actually already removed. If the teardown which manipulates the list runs first, emptying the list triggers the - at that point still bound - `live.list` to update. As the teardown for `live.list` hasn't run yet, its `exit` condition hasn't been flagged yet, which means it will still go down the `addFalseyIfEmpty` path. 

That path needs to use `after` to add the falsey body, which requires accessing `parentNode`, which is `null` because the element was already ripped out of the DOM.

Haven't been able to boil it down to a simplified reproduction yet. :(


In general, maybe some kind of globally accessible "is in teardown" flag would help to avoid these kind of races? Or a set of queues specific to operations occuring during teardown, which could be used to manually sequence operations into a guaranteed-correct order?

**Comment by rjgotten** [comment]
@justinbmeyer 

Just had a bit of an epiphany.
As the `can-dom-mutate` callbacks for `.onRemoval()` _always_ run after those for `.onNodeRemoval()` and helper teardowns built on `setup()` from `can-view-live` rely on the latter, I can stick the flushing of a queue into the former and test the concept of using a queue for (part of) the teardown work.

That is:

```js
// globally
const teardownQueue = new Queue( "post-teardown" );
canDomMutate.onRemoval( document.documentElement, () => {
  teardownQueue.flush();
});

// inside a helper
setup( el, bind, unbind );
function bind() { /* ... */ }
function unbind() {
  /* ... work which runs immediately ... */
  teardownQueue.enqueue(() => {
    /* ... work which should run after all pending teardowns ... */
  })
}
```

And indeed: this pattern solves my immediate problem.


Ofcourse, this would break if the firing conditions for `.onRemoval()` and `.onNodeRemoval()` ever change, so it'd be nice for something like this to be formally adopted and guarded against regressions via unit tests. :)


[EDIT]

Argh... no. Turns out it does not. Misread how those callbacks fire.
And my unit tests were now passing because of something else.

**Comment by rjgotten** [comment]
@justinbmeyer 

After a lot of digging, it turns out that this was a problem with bad data going into the compute argument for the `live.list` functionality.

Under certain conditions my own helper (which also uses `live.list`) was passing it the full contents of a DefineMap rather than a single DefineList. Said helper uses a map of lists, i.e. a multi-map, and at some point I extracted a list using `DefineMap.prototype.get()` with a null name, which triggers the behavior where it returns the whole map worth of keys.

Looks like this triggered some very strange observability bug somewhere.

Not sure you'd find that worth further investigation.
So feel free to just close this as a freak error.
